### ISSUE TITLE
404 on message publish

### ISSUE THREAD

**Issue by MuslimBeibytuly** [centrifugal/cent#23]
centrifugo is in docker-compose, using centrifugo/centrifugo:v3.0.1
config.json is:
```
{
  "token_hmac_secret_key": "CENTRIFUGO_SECRET",
  "api_key": "CENTRIFUGO_API_KEY",
  "admin_password": "Qwerty123",
  "admin_secret": "Qwerty123",
  "port": 9000,
  "namespaces": [
    {
      "name": "seed",
      "history_size": 16,
      "history_ttl": "512s",
      "recover": true
    }
  ],
  "allowed_origins": ["*"]
}

```

docker-compose.yml is:
```
centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v3.0.1
    command: centrifugo -c config.json
    volumes:
      - ./external/centrifugo:/centrifugo
```
repr is:

`self = <cent.core.Client object at 0x7f4f54c947c0>, url = 'http://centrifugo:9000', data = b'{"method": "publish", "params": {"channel": "seed:notifications", "data": {}, "skip_history": false}}'`

error is:

`cent.core.RequestException: wrong status code: 404`
